[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/Users/suzuke/miniconda3/lib"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/Users/suzuke/miniconda3/lib"
]
